/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Monday, September 2, 2024 at 9:37:07 PM
   By task:     Import Data Wizard
   
   Source file: Z:\tabelas\BAIE_IRRBB e CSRBB_Curvas.xlsx
   Server:      Local File System
   
   Output data: IN.OIS_EUR
   Server:      Local
   -------------------------------------------------------------------- */

/* --------------------------------------------------------------------
   This DATA step reads the data values from a temporary text file
   created by the Import Data wizard. The values within the temporary
   text file were extracted from the Excel source file.
   -------------------------------------------------------------------- */

%MACRO ImportCurvas;
/* Define a pasta onde os arquivos estão localizados */
	%let pasta = Z:\BANCO\tabelas\CURVAS; /* Define o caminho da pasta onde estão os arquivos */

/* Macro para listar e importar arquivos CSV */
	%MACRO importa_arquivos;
    /* Abre a pasta */
    	%let rc = %sysfunc(filename(fileref, "&pasta"));
    	%let did = %sysfunc(dopen(&fileref));

    /* Verifica se a pasta foi aberta com sucesso */
    	%if &did eq 0 %then %do;
        	%put ERROR: Não foi possível abrir a pasta &pasta;
     		%return;
    	%end;

    /* Contagem de arquivos na pasta */
    	%let nfiles = %sysfunc(dnum(&did));

    /* Loop para cada arquivo */
    	%do i = 1 %to &nfiles;
        	%let arquivo = %sysfunc(dread(&did, &i));

        /* Verifica se o arquivo tem a extensão CSV */
        	%if %lowcase(%scan(&arquivo, -1, .)) = csv %then %do;
            	%let caminho_arquivo = &pasta/&arquivo;
				%let nome_tabela = %scan(&arquivo, 1, .); 
            /* Chama a macro para importar o arquivo */
            	%importa(&caminho_arquivo);
        	%end;
    	%end;

    /* Fecha a pasta */
    	%let rc = %sysfunc(dclose(&did));	
	%MEND importa_arquivos;

/* Macro que importa o arquivo CSV */
	%MACRO importa(arquivo);
    	data IN.&nome_tabela; /* Nome do data set de saída com base no nome do arquivo */
	 	LENGTH
        	DATAS              8
        	INDEXANTE        $ 20
        	CURVA              8
			_100BP_P			   8
			_100BP_N			   8
        	PARALLEL_UP        8
        	PARALLEL_DOWN      8
        	SHORT_RATE_UP      8
        	SHORT_RATE_DOWN    8
			LONG_RATE_UP	   8
			LONG_RATE_DOWN	   8
        	STEEPENER          8
        	FLATTENER          8 ;
	
		LABEL
        	PARALLEL_UP      = "PARALLEL UP"
        	PARALLEL_DOWN    = "PARALLEL DOWN"
        	SHORT_RATE_UP          = "SHORT RATE UP"
        	SHORT_RATE_DOWN        = "SHORT RATE DOWN" ;
        	LONG_RATE_UP        = "LONG RATE UP" ;
        	LONG_RATE_DOWN        = "LONG RATE DOWN" ;
			_100BP_P                ="+100bp";
			_100BP_N                ="-100bp";
    	FORMAT
        	DATAS            		DATE9.
        	INDEXANTE        		$CHAR20.
        	CURVA         			F12.6
        	_100BP_P	       			F12.6
        	_100BP_N   		   			F12.6
        	PARALLEL_UP      		F12.6
        	PARALLEL_DOWN    		F12.6
        	SHORT_RATE_UP           F12.6
        	SHORT_RATE_DOWN         F12.6
        	LONG_RATE_UP        	F12.6
        	LONG_RATE_DOWN        	F12.6
        	STEEPENER        		F12.6
        	FLATTENER        		F12.6 ;
    	INFORMAT
			f1				 	BEST12.
        	DATAS            	mmddyy10.
        	INDEXANTE       	$CHAR20.
        	CURVA	         	BEST12.
			_100BP_P       	 	BEST12.
        	_100BP_N      	 	BEST12.
        	PARALLEL_UP      	BEST12.
        	PARALLEL_DOWN    	BEST12.
        	SHORT_RATE_UP       BEST12.
        	SHORT_RATE_DOWN     BEST12.
        	LONG_RATE_UP        BEST12.
        	LONG_RATE_DOWN      BEST12.
        	STEEPENER        	BEST12.
        	FLATTENER        	BEST12. ;
        INFILE "&arquivo" 
			dlm=',' 
			firstobs=10 
			lrecl=150 
			encoding="UTF-8" 
			termstr=CRLF 
			missover dsd;
    	INPUT
			f1				 : BEST12.
     		DATAS            : mmddyy10.
        	INDEXANTE        : $CHAR20.
        	CURVA         	 : BEST32.
			_100BP_P       	 : BEST32.	
			_100BP_N       	 : BEST32.	
        	PARALLEL_UP      : BEST32.
        	PARALLEL_DOWN    : BEST32.
        	SHORT_RATE_UP    : BEST32.
        	SHORT_RATE_DOWN  : BEST32.
			LONG_RATE_UP     : BEST32.
			LONG_RATE_DOWN   : BEST32.
        	STEEPENER        : BEST32.
        	FLATTENER        : BEST32. ;
	    RUN;
	%MEND importa;

/* Chama a macro para importar todos os arquivos */
	%importa_arquivos;
%MEND;


%MACRO ImportCurvasCSRBB();
/* Define a pasta onde os arquivos estão localizados */
	%let pasta = Z:\tabelas\CURVAS_CSRBB; /* Define o caminho da pasta onde estão os arquivos */

/* Macro para listar e importar arquivos CSV */
	%MACRO importa_arquivos_CSRBB;
    /* Abre a pasta */
    	%let rc = %sysfunc(filename(fileref, "&pasta"));
    	%let did = %sysfunc(dopen(&fileref));

    /* Verifica se a pasta foi aberta com sucesso */
    	%if &did eq 0 %then %do;
        	%put ERROR: Não foi possível abrir a pasta &pasta;
     		%return;
    	%end;

    /* Contagem de arquivos na pasta */
    	%let nfiles = %sysfunc(dnum(&did));

    /* Loop para cada arquivo */
    	%do i = 1 %to &nfiles;
        	%let arquivo = %sysfunc(dread(&did, &i));

        /* Verifica se o arquivo tem a extensão CSV */
        	%if %lowcase(%scan(&arquivo, -1, .)) = csv %then %do;
            	%let caminho_arquivo = &pasta/&arquivo;
				%let nome_tabela = %scan(&arquivo, 1, .); 
            /* Chama a macro para importar o arquivo */
            	%importa(&caminho_arquivo);
        	%end;
    	%end;

    /* Fecha a pasta */
    	%let rc = %sysfunc(dclose(&did));	
	%MEND;

/* Macro que importa o arquivo CSV */
	%MACRO importa(arquivo);
    	data IN.&nome_tabela; /* Nome do data set de saída com base no nome do arquivo */

    		LENGTH
        		CURVA            $ 9
        		RATING           $ 3
        		PAIS             $ 3
        		TENOR_MIN          8
        		TENOR_MAX          8
        		CHOQUE_UP          8
        		CHOQUE_DOWN        8 ;
    		DROP
        		F1 ;
    		FORMAT
        		CURVA            $CHAR9.
        		RATING           $CHAR3.
        		PAIS             $CHAR3.
        		TENOR_MIN        BEST3.
        		TENOR_MAX        BEST3.
        		CHOQUE_UP        BEST6.
        		CHOQUE_DOWN      BEST6. ;
    		INFORMAT
        		CURVA            $CHAR9.
        		RATING           $CHAR3.
        		PAIS             $CHAR3.
        		TENOR_MIN        BEST3.
        		TENOR_MAX        BEST3.
        		CHOQUE_UP        BEST6.
        		CHOQUE_DOWN      BEST6. ;
        INFILE "&arquivo" 
			dlm=',' 
			firstobs=10 
			lrecl=150 
			encoding="UTF-8" 
			termstr=CRLF 
			missover dsd;
    INPUT
        F1               : $1.
        CURVA            : $CHAR9.
        RATING           : $CHAR3.
        PAIS             : $CHAR3.
        TENOR_MIN        : ?? BEST3.
        TENOR_MAX        : ?? BEST3.
        CHOQUE_UP        : ?? COMMA6.
        CHOQUE_DOWN      : ?? COMMA6. ;

	RUN;

	%MEND importa;

/* Chama a macro para importar todos os arquivos */
	%importa_arquivos_CSRBB;
%MEND;
